# Hardware, Netzwerk & Logik
esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  flash_size: 8MB
  cpu_frequency: 240MHz
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      CONFIG_COMPILER_OPTIMIZATION_PERF: y
      CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: y
      CONFIG_ESPTOOLPY_FLASHSIZE_8MB: "y"
      CONFIG_ESPTOOLPY_FLASHMODE_QIO: y
      CONFIG_ESPTOOLPY_FLASHFREQ_80M: y
      CONFIG_SPIRAM_MODE_OCT: y
      CONFIG_SPIRAM_SPEED_80M: y
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: y
      CONFIG_SPIRAM_RODATA: y

# PSRAM Stabil auf 80MHz
psram:
  mode: octal
  speed: 80MHz

preferences:
  flash_write_interval: 5min

logger:
  level: WARN
  baud_rate: 0

api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none
  ap:
    ssid: "Waveshare-Fallback"
    password: !secret ap_password

captive_portal:

web_server:
  port: 80
  version: 2
  include_internal: true

i2c:
  - id: bus_a
    sda: GPIO8
    scl: GPIO9
    scan: true

ch422g:
  - id: ch422g_hub

time:
  - platform: homeassistant
    id: esptime
    on_time:
      - seconds: 0
        then:
          # Uhrzeit (Bleibt gleich)
          - lvgl.label.update:
              id: time_label
              text: !lambda |-
                auto now = id(esptime).now();
                if (!now.is_valid()) return "00:00";
                static char time_str[6];
                snprintf(time_str, sizeof(time_str), "%02d:%02d", now.hour, now.minute);
                return time_str;

          # DATUM (Neu: DD.MM.YYYY)
          - lvgl.label.update:
              id: date_label
              text: !lambda |-
                auto now = id(esptime).now();
                if (!now.is_valid()) return "";
                static char date_str[15];
                // Format geändert zu: 01.01.2024
                snprintf(date_str, sizeof(date_str), "%02d.%02d.%04d", now.day_of_month, now.month, now.year);
                return date_str;


globals:
  - id: timer_remaining_seconds
    type: int
    restore_value: no
    initial_value: '0'

  - id: timer_timer_active
    type: bool
    restore_value: no
    initial_value: 'false'

interval:
  - interval: 1s
    then:
      - lambda: |-
          if (id(timer_remaining_seconds) > 0 && id(timer_timer_active)) {
            id(timer_remaining_seconds)--;
          }
      - lvgl.label.update:
          id: timer_timer_label
          text: !lambda |-
            if (id(timer_remaining_seconds) <= 0) {
              return "Bereit";
            }

            int hours = id(timer_remaining_seconds) / 3600;
            int mins = (id(timer_remaining_seconds) % 3600) / 60;
            int secs = id(timer_remaining_seconds) % 60;

            static char buf[10];
            if (hours > 0) {
              snprintf(buf, sizeof(buf), "%d:%02d:%02d", hours, mins, secs);
            } else {
              snprintf(buf, sizeof(buf), "%02d:%02d", mins, secs);
            }
            return buf;
button:
  - platform: restart
    name: "Display Neustart"
    id: btn_restart
    entity_category: "config"

switch:
  - platform: safe_mode
    name: "Display Safe Mode"
    id: device_safe_mode
    entity_category: "config"
